### ISSUE TITLE
Zombie fails after upgrading jQuery from v1.11 to v1.12

### ISSUE THREAD

**Issue by jlchereau** [assaf/zombie#1031]
```
TypeError: j.getClientRects is not a function
    at k (http://code.jquery.com/jquery-1.12.2.min.js:3:26891)
    at Object.n.extend.pixelMarginRight (http://code.jquery.com/jquery-1.12.2.min.js:3:25936)
    at a.getComputedStyle.Sa (http://code.jquery.com/jquery-1.12.2.min.js:3:27544)
    at Function.n.extend.css (http://code.jquery.com/jquery-1.12.2.min.js:3:30957)
    at Object.n.cssHooks.(anonymous function).get (http://code.jquery.com/jquery-1.12.2.min.js:3:31155)
    at Function.n.extend.css (http://code.jquery.com/jquery-1.12.2.min.js:3:30929)
    at http://code.jquery.com/jquery-1.12.2.min.js:5:534
    at Y (http://code.jquery.com/jquery-1.12.2.min.js:3:4661)
    at n.fn.(anonymous function) [as width] (http://code.jquery.com/jquery-1.12.2.min.js:5:305)
    at HTMLDocument.<anonymous> (http://localhost:3000/support/assets/home.bundle.js?v=v0.0.9:3:2793)
    in http://localhost:3000/support/
```

The statement that fails in home.bundle.js since the jQuery upgrade is $.width in: 

```
var el = $('#an_id');
var w = el.width();
```

**Comment by jlchereau** [comment]
Any feedback about this issue?

**Comment by vosgaust** [comment]
so is jQuery 1.12 not supported in latest versions of zombie? any news about this issue?

**Comment by jlchereau** [comment]
See changes to jQuery in https://github.com/jquery/jquery/issues/2804.

**Comment by jlchereau** [comment]
This is actually an issue in jsdom which has been fixed at
https://github.com/tmpvar/jsdom/blob/master/lib/jsdom/living/nodes/Element-impl.js#L412
Zombie uses jsdom v5.3 and latest version as of today is v9.1.
Please upgrade.

**Comment by fishcharlie** [comment]
Any updates or solutions to this?

**Comment by EvanK** [comment]
PR #990 proposes a fix, but it hasnt seen activity since May 😞

**Comment by mdlavin** [comment]
I recently got permission to merge changes and publish new fixes and I'm happy to help get issues with clear fixes resolved.  Let me checkout the state of that PR and hopefully it's straightforward to merge.

**Comment by mdlavin** [comment]
I merged adoption of jsdom 7.x. Is anybody interested in this enough to test the version in master to check for some regressions?  The travis builds are still green, and I'll bump the major version to 5.x to avoid surprises, but more testing is always good.

**Comment by fishcharlie** [comment]
@mdlavin This hasn't been pushed to NPM yet correct?

**Comment by fishcharlie** [comment]
I'm getting the error `Error: Cannot find module 'zombie'` for some reason. Probably just me. The following line is in my package.json file `"zombie": "github:assaf/zombie",`. Any ideas or is this a bug?

**Comment by mdlavin** [comment]
Right, it has not yet been pushed. I was hoping somebody could confirm it
fixes it. I can push a new version to npm tomorrow if nobody else has time
to test.

**Comment by mdlavin** [comment]
@fishcharlie sorry about that, I forgot that zombie is a hard project to test early because it doesn't allow easily being added to the package.json file directly.  The compilation step causes it to not be installed correctly. I'll try to add a testcase for it and release a new version sometime tomorrow.

**Comment by mdlavin** [comment]
Unfortunately adoption jsdom 7.x is not enough and looks like 9.x adoption is needed. I put a PR up that included a testcase and verified that the test fails even with jsdom 7.x merged.

**Comment by mdlavin** [comment]
I took a couple hour stab at adopting jsdom 8.x and it is not trivial. For now, I think jquery 1.12 is going to have to wait until somebody gets motivated enough to adopt jsdom 8.x

**Comment by l2aelba** [comment]
@mdlavin Any update ? I hope this will fix ASAP, I cant login a form with Zombie lol

**Comment by mdlavin** [comment]
Adopting jsdom 8/9 as the fix for your problem was harder than I wanted.  It should be pretty easy to add a dummy implementation for getClientRects() just to get past that specific failure. I'll try that and see how it goes

**Comment by mdlavin** [comment]
Add a stub implementation of getClientRects() was straightforward. I've published 5.0.1 with a fix for this specific failure.

**Comment by jlchereau** [comment]
It works for me. Thx.
